
spring:
  profiles:
    active: dev
  datasource:
    password:
    url: jdbc:mysql://root:CjAaIuZJ26Xqov8lWM39@containers-us-west-28.railway.app:7508/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true



#mysql://root:CjAaIuZJ26Xqov8lWM39@containers-us-west-28:railway:app:7508/railway